title: Bathroom Finder Docs
description: Documentation for the Bathroom Finder project
theme: just-the-docs

url: https://green-kittens.github.io

aux_links:
  GitHub Organization: https://github.com/Green-Kittens
